In [2]:
# In this we are going to load Air quality data from kaggle
import pandas as pd
df=pd.read_csv("globalAirQuality.csv")

In [3]:
df[['country','city']].head()  # In this code of line i am selecting country and city both column 
# and the above is the way to select an multiple columns from dataSet...
# Then after i am using head() inbuilt method to get only first five dataSets values....

  country      city
0      US  New York
1      US  New York
2      US  New York
3      US  New York
4      US  New York

# Filtering data

In [4]:
df[(df['aqi']>100)][['city','country']]

           city country
0      New York      US
3      New York      US
6      New York      US
7      New York      US
8      New York      US
...         ...     ...
17991    Zurich      CH
17993    Zurich      CH
17995    Zurich      CH
17996    Zurich      CH
17997    Zurich      CH

[9721 rows x 2 columns]

# Handleing missing values with pandas inbuilt methods

In [5]:
df_1=pd.read_csv("raw_data.csv")

In [6]:
df_1

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [7]:
clean_dataFrame=df_1.copy()

In [8]:
clean_dataFrame['name']=clean_dataFrame['name'].fillna("Unknown")
clean_dataFrame['age']=clean_dataFrame['age'].fillna(clean_dataFrame['age'].mean())
clean_dataFrame['country']=clean_dataFrame['country'].ffill()
clean_dataFrame['gender']=clean_dataFrame['gender'].bfill().ffill()
clean_dataFrame['income']=clean_dataFrame['income'].fillna(clean_dataFrame['income'].mean())

In [9]:
clean_dataFrame

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  57600.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6       Unknown  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00   India     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA     Male  58000.0

# Handling duplicates

In [10]:
# For duplicate pandas had .duplicated() method that will return a series after search duplicates 
# row wise 
# And to deleting duplicates it had .drop_duplicates() method that will remove whole row from dataframe..

# Appying Feature Engineering

In [11]:
clean_dataFrame['Income_Tax']=clean_dataFrame['income'].apply(lambda x: "20%" if x>=50000 else "10%")

In [59]:
clean_dataFrame

    id          name    age country   gender   income Income_Tax
0    1      John Doe  29.00     USA     Male  55000.0        20%
1    1      John Doe  29.00     USA     Male  55000.0        20%
2    2    Jane Smith  32.75  Canada   Female  62000.0        20%
3    3          Alex  32.75     USA  Unknown  47000.0        10%
4    4  Maria Garcia  34.00   Spain   Female  57600.0        20%
5    5        Li Wei  27.00   China     Male  51000.0        20%
6    6       Unknown  45.00   India   Female  73000.0        20%
7    7    Ahmed Khan  38.00   India     Male  68000.0        20%
8    8    Rachel Lee  29.00     USA   Female  62000.0        20%
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0        10%
10  10   Emily Davis  31.00     USA     Male  58000.0        20%

In [12]:
# map method 
gender_map={"Male":"M","Female":"F","Unknown":"U"}
clean_dataFrame['gender']=clean_dataFrame['gender'].map(gender_map)

In [13]:
clean_dataFrame

    id          name    age country gender   income Income_Tax
0    1      John Doe  29.00     USA      M  55000.0        20%
1    1      John Doe  29.00     USA      M  55000.0        20%
2    2    Jane Smith  32.75  Canada      F  62000.0        20%
3    3          Alex  32.75     USA      U  47000.0        10%
4    4  Maria Garcia  34.00   Spain      F  57600.0        20%
5    5        Li Wei  27.00   China      M  51000.0        20%
6    6       Unknown  45.00   India      F  73000.0        20%
7    7    Ahmed Khan  38.00   India      M  68000.0        20%
8    8    Rachel Lee  29.00     USA      F  62000.0        20%
9    9   Carlos Ruiz  32.75  Mexico      M  45000.0        10%
10  10   Emily Davis  31.00     USA      M  58000.0        20%

In [74]:
clean_dataFrame.assign(Income_Rating= clean_dataFrame['income'].apply(lambda x:"Good" if x>50000 else "average"))

    id          name    age country gender   income Income_Tax Income_Rating
0    1      John Doe  29.00     USA      M  55000.0        20%          Good
1    1      John Doe  29.00     USA      M  55000.0        20%          Good
2    2    Jane Smith  32.75  Canada      F  62000.0        20%          Good
3    3          Alex  32.75     USA      U  47000.0        10%       average
4    4  Maria Garcia  34.00   Spain      F  57600.0        20%          Good
5    5        Li Wei  27.00   China      M  51000.0        20%          Good
6    6       Unknown  45.00   India      F  73000.0        20%          Good
7    7    Ahmed Khan  38.00   India      M  68000.0        20%          Good
8    8    Rachel Lee  29.00     USA      F  62000.0        20%          Good
9    9   Carlos Ruiz  32.75  Mexico      M  45000.0        10%       average
10  10   Emily Davis  31.00     USA      M  58000.0        20%          Good

In [84]:
clean_dataFrame.groupby("gender")[['income','Income_Tax']].agg(["max","min"])

         income          Income_Tax
            max      min        max  min
gender
F       73000.0  57600.0        20%  20%
M       68000.0  45000.0        20%  10%
U       47000.0  47000.0        10%  10%