# Pandas DataFrame

In [14]:
import pandas as pd
# There are servel ways to create DataFrame 
info={
    "Name":['Harry','Roy','Jemin','George'],
    "Age":[21,22,20,23],
    "gpa":[8.09,8.79,7.78,8.08]
}

# now to create a dataFrame this python dictionary we have to pass this dicationary as an argument to DataFrame method
df=pd.DataFrame(info)

In [3]:
df  # this will show how does the pandas DataFrame looks like

     Name  Age   gpa
0   Harry   21  8.09
1     Roy   22  8.79
2   Jemin   20  7.78
3  George   23  8.08

In [4]:
# Creating dataFrames with the nested list 
nesListFrame=pd.DataFrame([[1,2,3],[4,5,6]],columns=["A","B","C",])

In [5]:
nesListFrame

   A  B  C
0  1  2  3
1  4  5  6

In [6]:
# To get the data from CSV file pandas librarie had a method
# pd.read_csv("FILE_NAME.csv")

# To read from the JSON file pandas had a method that is 
# pd.read_json("FILE_NAME.json")

# Reading Data from CSV file

In [9]:
df=pd.read_csv("employee_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

# DataFrame Methods

In [10]:
df.head()  # This method is used to return intial 5 rows from the dataFrame...

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [11]:
df.tail() # this method is used return last 5 rows values from the dataFrame this are by default if we want more or less then we can pass that number value as argument to the method

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [12]:
df.sample(5)

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
7   8  Hannah   26  Marketing   47000
4   5     Eva   38         IT   65000
1   2     Bob   32         IT   72000
9  10   Julia   30    Finance   60000